[project]
name = "mine-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"kg-gen",
	"dspy",
    "nltk",
    "pydantic>=2.0.0",
	"networkx",
	"sentence-transformers",
]
